name: GOESTuner Build

on: push

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y golang libsoapysdr-dev soapysdr0.8-module-all git
      - name: build dependencies
        run: |
          git clone https://github.com/opensatelliteproject/libsathelper.git
          cd libsathelper
          git apply ../libsathelper.patch
          make libcorrect
          sudo make libcorrect-install
          make
          sudo make install
          cd ..
      - name: build
        run: go build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'goestuner-$(git rev-parse --short HEAD)'
          path: goestuner
